name = "liminall-node-engine"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "liminall-node"
database_id = "PASTE_YOUR_D1_DATABASE_ID_HERE"

[[r2_buckets]]
binding = "NODE_IMAGES"
bucket_name = "liminall-node-images"
